#!/bin/bash

./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/L1_sixm250obs/L1_sixm250obs.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/Linf_520c/Linf_520c.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/a2864/a2864.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/bdry2/bdry2.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/cont1/cont1.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/cont11/cont11.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/datt256_lp/datt256_lp.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/dlr1/dlr1.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/ex10/ex10.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/fhnw-binschedule1/fhnw-binschedule1.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/fome13/fome13.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/graph40-40/graph40-40.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/irish-electricity/irish-electricity.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/neos/neos.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/neos3/neos3.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/neos-3025225/neos-3025225.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/neos-5052403-cygnet/neos-5052403-cygnet.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/neos-5251015/neos-5251015.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/ns1687037/ns1687037.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/ns1688926/ns1688926.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/nug08-3rd/nug08-3rd.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/pds-100/pds-100.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/physiciansched3-3/physiciansched3-3.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/qap15/qap15.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/rail02/rail02.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/rail4284/rail4284.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/rmine15/rmine15.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/s82/s82.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/s100/s100.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/s250r10/s250r10.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/savsched1/savsched1.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/scpm1/scpm1.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/shs1023/shs1023.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/square41/square41.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/stat96v2/stat96v2.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/stormG2_1000/stormG2_1000.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/stp3d/stp3d.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/supportcase10/supportcase10.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/tpl-tub-ws1617/tpl-tub-ws1617.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/woodlands09/woodlands09.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/Dual2_5000/Dual2_5000.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/Primal2_1000/Primal2_1000.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/thk_48/thk_48.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/thk_63/thk_63.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/L1_sixm1000obs/L1_sixm1000obs.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/L2CTA3D/L2CTA3D.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/degme/degme.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/dlr2/dlr2.mps h_param.txt 1e-4
./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/set-cover-model/set-cover-model.mps h_param.txt 1e-4

#./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/physiciansched3-3/physiciansched3-3.mps evo.txt 1e-4
#./cpp/build/run_benchmark ~/rapids/db_cuopt/cuopt/datasets/linear_programming/ns1687037/ns1687037.mps evo.txt 1e-4
